apiVersion: v2
name: pms
description: Single-tenant self-hosted Project Management System
type: application
version: 1.0.8
appVersion: "1.0.8"
keywords:
  - pms
  - project-management
maintainers:
  - name: PMS contributors
