package com.brad.pms.ops;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assumptions;
import org.springframework.boot.env.YamlPropertySourceLoader;
import org.springframework.core.env.PropertySource;
import org.springframework.core.io.ClassPathResource;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

class MysqlContributorStackTest {

    @Test
    void mysqlProfileKeepsExplicitCredentialsAndEnablesFlyway() throws Exception {
        List<PropertySource<?>> sources = new YamlPropertySourceLoader().load(
                "mysql", new ClassPathResource("application-mysql.yml"));
        PropertySource<?> source = sources.get(0);

        assertThat(source.getProperty("spring.datasource.username"))
                .isEqualTo("${MYSQL_USER}");
        assertThat(source.getProperty("spring.datasource.password"))
                .isEqualTo("${MYSQL_PASSWORD}");
        assertThat(source.getProperty("spring.flyway.enabled")).isEqualTo(true);
        assertThat(source.getProperty("spring.datasource.url"))
                .asString()
                .contains("${MYSQL_DB:pms}");
    }

    @Test
    void mysqlComposeIsALocalDatabaseOnlyStack() throws Exception {
        String compose = Files.readString(Path.of("docker-compose.mysql.yml"));

        assertThat(compose).contains("image: mysql:8.4");
        assertThat(compose).contains("127.0.0.1:${MYSQL_PORT:-3306}:3306");
        assertThat(compose).contains("MYSQL_DATABASE: ${MYSQL_DB:-pms}");
        assertThat(compose).contains("healthcheck:");
        assertThat(compose).contains("mysqladmin ping");
        assertThat(compose).doesNotContain("oceanbase/oceanbase");
        assertThat(compose).doesNotContain("pms-backend");
        assertThat(compose).doesNotContain("pms-front");
        assertThat(compose).doesNotContain("MYSQL_DATABASE: brad_pms");
        assertThat(compose).doesNotContain("MYSQL_DB:-brad_pms");
    }

    @Test
    void mysqlExampleEnvUsesFictionalBootstrapIdentity() throws Exception {
        String env = Files.readString(Path.of(".env.mysql.example"));

        assertThat(env).contains("MYSQL_DB=pms");
        assertThat(env).contains("PMS_BOOTSTRAP_ADMIN_EMAIL=admin@example.com");
        assertThat(env).contains("PMS_BOOTSTRAP_ADMIN_NAME_ZH=系统管理员");
        assertThat(env).contains("PMS_BOOTSTRAP_ADMIN_PASSWORD=PmsAdmin123!");
        assertThat(env).contains("replace_with_a_random_secret_at_least_32_bytes");
        assertThat(env).contains("PMS_NOTIFICATION_STARTUP_CHECK=false");
        assertThat(env).contains("http://localhost:5173");
        assertThat(env).doesNotContain("MYSQL_DB=brad_pms");
    }

    @Test
    void startScriptUsesMysqlProfileAndDoesNotInventSecrets() throws Exception {
        String start = Files.readString(Path.of("scripts/start-local-mysql.sh"));
        String stop = Files.readString(Path.of("scripts/stop-local-mysql.sh"));

        assertThat(start).contains("docker-compose.mysql.yml");
        assertThat(start).contains("--spring.profiles.active=mysql");
        assertThat(start).contains("PMS_JWT_SECRET is required and must not be generated by this script");
        assertThat(start).contains("PMS_BOOTSTRAP_ADMIN_EMAIL");
        assertThat(start).contains("MYSQL_USER is required");
        assertThat(start).doesNotContain("flyway.enabled=false");
        assertThat(stop).contains("docker-compose.mysql.yml");
        assertThat(stop).contains("--down");
    }

    @Test
    void mysqlComposeConfigIsValidWhenDockerIsAvailable() throws Exception {
        Process version = new ProcessBuilder("docker", "compose", "version")
                .redirectErrorStream(true)
                .start();
        boolean finished = version.waitFor(8, TimeUnit.SECONDS);
        Assumptions.assumeTrue(finished && version.exitValue() == 0, "docker compose is not available");

        Process config = new ProcessBuilder(
                "docker", "compose",
                "-f", "docker-compose.mysql.yml",
                "--env-file", ".env.mysql.example",
                "config", "--quiet")
                .directory(Path.of(".").toFile())
                .redirectErrorStream(true)
                .start();
        boolean configFinished = config.waitFor(20, TimeUnit.SECONDS);
        String output = new String(config.getInputStream().readAllBytes());
        assertThat(configFinished).isTrue();
        assertThat(config.exitValue())
                .as("docker compose config failed: %s", output)
                .isZero();
    }
}
