package com.brad.pms.common.enums;

public enum ProjectAttentionType {
    PROJECT_MANAGER_MISSING,
    CURRENT_NODE_OWNER_MISSING,
    CURRENT_NODE_SCHEDULE_MISSING,
    CURRENT_NODE_TASK_MISSING,
    FUTURE_NODE_OWNER_MISSING,
    FUTURE_NODE_SCHEDULE_MISSING,
    FUTURE_NODE_TASK_MISSING,
    TASK_OVERDUE,
    TASK_DUE_TODAY,
    TASK_DUE_SOON,
    HIGH_RISK_OPEN
}
