#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
JAR_PATH="${PMS_JAR_PATH:-$PROJECT_DIR/target/pms-backend-0.1.0.jar}"
RUN_DIR="${PMS_RUN_DIR:-$PROJECT_DIR/.run}"
PID_FILE="$RUN_DIR/pms-backend.pid"
LOG_FILE="$RUN_DIR/pms-backend.log"

if [[ -n "${PMS_ENV_FILE:-}" ]]; then
  if [[ ! -f "$PMS_ENV_FILE" ]]; then
    echo "PMS_ENV_FILE does not exist: $PMS_ENV_FILE" >&2
    exit 2
  fi
  set -a
  # shellcheck disable=SC1090
  source "$PMS_ENV_FILE"
  set +a
fi

: "${OCEANBASE_HOST:=127.0.0.1}"
: "${OCEANBASE_PORT:=2881}"
: "${OCEANBASE_DATABASE:=brad_pms}"
if [[ -z "${OCEANBASE_USER:-}" ]]; then
  echo "OCEANBASE_USER is required" >&2
  exit 2
fi
if [[ -z "${OCEANBASE_PASSWORD+x}" ]]; then
  echo "OCEANBASE_PASSWORD must be set explicitly (it may be empty for a local account)" >&2
  exit 2
fi
if [[ -z "${PMS_JWT_SECRET+x}" || -z "$PMS_JWT_SECRET" ]]; then
  echo "PMS_JWT_SECRET is required and must not be generated by this script" >&2
  exit 2
fi

secret_bytes="$(printf '%s' "$PMS_JWT_SECRET" | wc -c | tr -d '[:space:]')"
if ! [[ "$secret_bytes" =~ ^[0-9]+$ ]] || (( secret_bytes < 32 )); then
  echo "PMS_JWT_SECRET must contain at least 32 UTF-8 bytes" >&2
  exit 2
fi

if [[ ! -f "$JAR_PATH" ]]; then
  echo "backend jar not found: $JAR_PATH" >&2
  echo "run: mvn -q -DskipTests package" >&2
  exit 2
fi
if ! command -v java >/dev/null 2>&1; then
  echo "java is required" >&2
  exit 2
fi
if ! command -v nc >/dev/null 2>&1; then
  echo "nc is required to check the OceanBase port" >&2
  exit 2
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to check backend readiness" >&2
  exit 2
fi
if ! nc -z -w 3 "$OCEANBASE_HOST" "$OCEANBASE_PORT" >/dev/null 2>&1; then
  echo "OceanBase is not reachable at $OCEANBASE_HOST:$OCEANBASE_PORT" >&2
  exit 1
fi

if [[ -f "$PID_FILE" ]]; then
  old_pid="$(tr -d '[:space:]' < "$PID_FILE")"
  if [[ "$old_pid" =~ ^[0-9]+$ ]] && kill -0 "$old_pid" 2>/dev/null; then
    old_command="$(ps -p "$old_pid" -o command= 2>/dev/null || true)"
    if [[ "$old_command" == *pms-backend* ]]; then
      echo "PMS backend is already running (pid=$old_pid)"
      exit 0
    fi
  fi
  rm -f "$PID_FILE"
fi

mkdir -p "$RUN_DIR"
umask 077
{
  printf 'Starting PMS backend with OceanBase at %s:%s/%s\n' \
    "$OCEANBASE_HOST" "$OCEANBASE_PORT" "$OCEANBASE_DATABASE"
  printf 'Log file: %s\n' "$LOG_FILE"
} >&2

nohup env \
  OCEANBASE_HOST="$OCEANBASE_HOST" \
  OCEANBASE_PORT="$OCEANBASE_PORT" \
  OCEANBASE_DATABASE="$OCEANBASE_DATABASE" \
  OCEANBASE_USER="$OCEANBASE_USER" \
  OCEANBASE_PASSWORD="$OCEANBASE_PASSWORD" \
  PMS_JWT_SECRET="$PMS_JWT_SECRET" \
  java -jar "$JAR_PATH" --spring.profiles.active=oceanbase \
  >>"$LOG_FILE" 2>&1 &
pid=$!
printf '%s\n' "$pid" > "$PID_FILE"

for _ in $(seq 1 30); do
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "PMS backend exited during startup; inspect $LOG_FILE" >&2
    rm -f "$PID_FILE"
    exit 1
  fi
  status="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 2 \
    "http://127.0.0.1:${PMS_SERVER_PORT:-8080}/api/auth/me" 2>/dev/null || true)"
  if [[ "$status" == "200" || "$status" == "401" ]]; then
    echo "PMS backend started (pid=$pid, HTTP $status)"
    exit 0
  fi
  sleep 1
done

echo "PMS backend did not become ready within 30 seconds; inspect $LOG_FILE" >&2
exit 1
