#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.mysql.yml"
JAR_PATH="${PMS_JAR_PATH:-$PROJECT_DIR/target/pms-backend-1.0.0.jar}"
RUN_DIR="${PMS_RUN_DIR:-$PROJECT_DIR/.run}"
PID_FILE="$RUN_DIR/pms-backend.pid"
LOG_FILE="$RUN_DIR/pms-backend.log"

if [[ -z "${PMS_ENV_FILE:-}" && -f "$PROJECT_DIR/.env.mysql.local" ]]; then
  PMS_ENV_FILE="$PROJECT_DIR/.env.mysql.local"
fi

COMPOSE_ENV_FILE=""
if [[ -n "${PMS_ENV_FILE:-}" ]]; then
  if [[ ! -f "$PMS_ENV_FILE" ]]; then
    echo "PMS_ENV_FILE does not exist: $PMS_ENV_FILE" >&2
    exit 2
  fi
  COMPOSE_ENV_FILE="$PMS_ENV_FILE"
  set -a
  # shellcheck disable=SC1090
  source "$PMS_ENV_FILE"
  set +a
fi

: "${MYSQL_HOST:=127.0.0.1}"
: "${MYSQL_PORT:=3306}"
: "${MYSQL_DB:=pms}"
: "${PMS_DEPLOYMENT_ENV:=development}"
: "${PMS_NOTIFICATION_STARTUP_CHECK:=false}"
: "${PMS_PASSWORD_RESET_EXPOSE_TOKEN:=true}"
: "${PMS_INVITATION_EXPOSE_TOKEN:=true}"
: "${PMS_CORS_ALLOWED_ORIGINS:=http://localhost:5173,http://127.0.0.1:5173}"

if [[ -z "${MYSQL_USER:-}" ]]; then
  echo "MYSQL_USER is required" >&2
  exit 2
fi
if [[ -z "${MYSQL_PASSWORD:-}" ]]; then
  echo "MYSQL_PASSWORD is required" >&2
  exit 2
fi
if [[ -z "${MYSQL_ROOT_PASSWORD:-}" ]]; then
  echo "MYSQL_ROOT_PASSWORD is required to start docker-compose.mysql.yml" >&2
  exit 2
fi
if [[ -z "${PMS_JWT_SECRET+x}" || -z "$PMS_JWT_SECRET" ]]; then
  echo "PMS_JWT_SECRET is required and must not be generated by this script" >&2
  exit 2
fi

secret_bytes="$(printf '%s' "$PMS_JWT_SECRET" | wc -c | tr -d '[:space:]')"
if ! [[ "$secret_bytes" =~ ^[0-9]+$ ]] || (( secret_bytes < 32 )); then
  echo "PMS_JWT_SECRET must contain at least 32 UTF-8 bytes" >&2
  exit 2
fi

if [[ -z "${PMS_BOOTSTRAP_ADMIN_EMAIL:-}" ]]; then
  echo "PMS_BOOTSTRAP_ADMIN_EMAIL is required for the first empty-database start" >&2
  exit 2
fi
if [[ -z "${PMS_BOOTSTRAP_ADMIN_PASSWORD:-}" || "${#PMS_BOOTSTRAP_ADMIN_PASSWORD}" -lt 12 ]]; then
  echo "PMS_BOOTSTRAP_ADMIN_PASSWORD must be at least 12 characters" >&2
  exit 2
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required to start the local MySQL 8 stack" >&2
  exit 2
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose is required to start the local MySQL 8 stack" >&2
  exit 2
fi
if ! command -v java >/dev/null 2>&1; then
  echo "java is required" >&2
  exit 2
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to check backend readiness" >&2
  exit 2
fi

compose() {
  if [[ -n "$COMPOSE_ENV_FILE" ]]; then
    docker compose -f "$COMPOSE_FILE" --env-file "$COMPOSE_ENV_FILE" "$@"
  else
    docker compose -f "$COMPOSE_FILE" "$@"
  fi
}

compose up -d

mysql_ready=0
for _ in $(seq 1 45); do
  health="$(compose ps mysql --format '{{.Health}}' 2>/dev/null || true)"
  if [[ "$health" == "healthy" ]]; then
    mysql_ready=1
    break
  fi
  sleep 2
done
if [[ "$mysql_ready" -ne 1 ]]; then
  echo "MySQL 8 did not become healthy; inspect: docker compose -f $COMPOSE_FILE logs mysql" >&2
  echo "If port ${MYSQL_PORT} is already in use, set MYSQL_PORT in .env.mysql.local" >&2
  exit 1
fi

if [[ ! -f "$JAR_PATH" ]]; then
  if ! command -v mvn >/dev/null 2>&1; then
    echo "backend jar not found: $JAR_PATH" >&2
    echo "run: mvn -q -DskipTests package" >&2
    exit 2
  fi
  echo "backend jar not found; packaging with Maven" >&2
  (cd "$PROJECT_DIR" && mvn -q -DskipTests package)
fi
if [[ ! -f "$JAR_PATH" ]]; then
  echo "backend jar not found after package: $JAR_PATH" >&2
  exit 2
fi

if [[ -f "$PID_FILE" ]]; then
  old_pid="$(tr -d '[:space:]' < "$PID_FILE")"
  if [[ "$old_pid" =~ ^[0-9]+$ ]] && kill -0 "$old_pid" 2>/dev/null; then
    old_command="$(ps -p "$old_pid" -o command= 2>/dev/null || true)"
    if [[ "$old_command" == *pms-backend* ]]; then
      echo "PMS backend is already running (pid=$old_pid)"
      exit 0
    fi
  fi
  rm -f "$PID_FILE"
fi

upload_dir="${PMS_UPLOAD_DIR:-$HOME/.pms-dev/uploads}"
if [[ ! "$upload_dir" = /* ]]; then
  echo "PMS_UPLOAD_DIR must be an absolute path outside the application directory" >&2
  exit 2
fi
mkdir -p "$upload_dir"

mkdir -p "$RUN_DIR"
umask 077
{
  printf 'Starting PMS backend with MySQL 8 at %s:%s/%s\n' \
    "$MYSQL_HOST" "$MYSQL_PORT" "$MYSQL_DB"
  printf 'Log file: %s\n' "$LOG_FILE"
} >&2

nohup env \
  MYSQL_HOST="$MYSQL_HOST" \
  MYSQL_PORT="$MYSQL_PORT" \
  MYSQL_DB="$MYSQL_DB" \
  MYSQL_USER="$MYSQL_USER" \
  MYSQL_PASSWORD="$MYSQL_PASSWORD" \
  PMS_JWT_SECRET="$PMS_JWT_SECRET" \
  PMS_BOOTSTRAP_ADMIN_EMAIL="$PMS_BOOTSTRAP_ADMIN_EMAIL" \
  PMS_BOOTSTRAP_ADMIN_PASSWORD="$PMS_BOOTSTRAP_ADMIN_PASSWORD" \
  PMS_BOOTSTRAP_ADMIN_USERNAME="${PMS_BOOTSTRAP_ADMIN_USERNAME:-}" \
  PMS_BOOTSTRAP_ADMIN_NAME_ZH="${PMS_BOOTSTRAP_ADMIN_NAME_ZH:-}" \
  PMS_UPLOAD_DIR="$upload_dir" \
  PMS_CORS_ALLOWED_ORIGINS="$PMS_CORS_ALLOWED_ORIGINS" \
  PMS_DEPLOYMENT_ENV="$PMS_DEPLOYMENT_ENV" \
  PMS_NOTIFICATION_STARTUP_CHECK="$PMS_NOTIFICATION_STARTUP_CHECK" \
  PMS_PASSWORD_RESET_EXPOSE_TOKEN="$PMS_PASSWORD_RESET_EXPOSE_TOKEN" \
  PMS_INVITATION_EXPOSE_TOKEN="$PMS_INVITATION_EXPOSE_TOKEN" \
  java -jar "$JAR_PATH" --spring.profiles.active=mysql \
  >>"$LOG_FILE" 2>&1 &
pid=$!
printf '%s\n' "$pid" > "$PID_FILE"

for _ in $(seq 1 60); do
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "PMS backend exited during startup; inspect $LOG_FILE" >&2
    rm -f "$PID_FILE"
    exit 1
  fi
  status="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 2 \
    "http://127.0.0.1:${PMS_SERVER_PORT:-8080}/api/auth/me" 2>/dev/null || true)"
  if [[ "$status" == "200" || "$status" == "401" ]]; then
    echo "PMS backend started (pid=$pid, HTTP $status)"
    echo "Frontend: from the sibling pms-front repo run  pnpm dev"
    exit 0
  fi
  sleep 1
done

echo "PMS backend did not become ready within 60 seconds; inspect $LOG_FILE" >&2
exit 1
