{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pms.fullname" . }}-secrets
  labels:
    {{- include "pms.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSecret: {{ .Values.secret.jwtSecret | quote }}
  mysqlPassword: {{ .Values.secret.mysqlPassword | quote }}
  bootstrapAdminEmail: {{ .Values.secret.bootstrapAdminEmail | quote }}
  bootstrapAdminPassword: {{ .Values.secret.bootstrapAdminPassword | quote }}
  bootstrapAdminNameZh: {{ .Values.secret.bootstrapAdminNameZh | quote }}
{{- end }}
