CREATE TABLE project_node_release_baseline (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id          BIGINT       NOT NULL,
    node_id             BIGINT       NOT NULL,
    release_version     VARCHAR(120),
    release_window_start TIMESTAMP NULL,
    release_window_end   TIMESTAMP NULL,
    release_type        VARCHAR(32)  NOT NULL DEFAULT 'GRAY' COMMENT 'FULL全量 GRAY灰度 HOTFIX紧急修复',
    package_ready       BOOLEAN      NOT NULL DEFAULT FALSE,
    config_confirmed    BOOLEAN      NOT NULL DEFAULT FALSE,
    rollback_ready      BOOLEAN      NOT NULL DEFAULT FALSE,
    monitoring_confirmed BOOLEAN     NOT NULL DEFAULT FALSE,
    on_call_confirmed   BOOLEAN      NOT NULL DEFAULT FALSE,
    decision_result     VARCHAR(32)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待决策 APPROVED同意发布 DEFERRED延期 CANCELLED取消',
    decision_note       VARCHAR(2000),
    handover_notes      VARCHAR(2000),
    observation_items   VARCHAR(2000),
    emergency_contact   VARCHAR(500),
    version             INT          NOT NULL DEFAULT 0,
    created_by          BIGINT,
    created_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_node_release_baseline_project_node (project_id, node_id),
    INDEX idx_node_release_baseline_node (node_id)
);
